# Generated by Django 3.2.4 on 2021-09-22 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
